### ISSUE TITLE
Only push branches having the package

### ISSUE THREAD

**Issue by kdambekalns** [neos/slicer#17]
Unless #14 is done already…

Push branches only, if the package being worked on has the package already/still (e.g. `neos/content-repository` no longer exists in `9.0`.)

**Comment by kitsunet** [comment]
Done with https://github.com/neos/slicer/commit/9bacf6ded80c42278754bf692d8183a086977571 (and the little followup)

**Comment by kdambekalns** [comment]
This is about packages that no longer exist in e.g. 9.0 and should not have that branch pushed to the split repository. So, not done yet.

**Comment by kitsunet** [comment]
It does prevent that though, if there is no composer.json no push..

**Comment by kitsunet** [comment]
so if the respective ref has a composer.json it will output the object ids and such, otherwise an empty line.

**Comment by kitsunet** [comment]
Ok interesting, it DID recreate the 9.0 branch on content-repository just now, so something is still amiss, but this seemed to work fine in tests locally...

**Comment by kitsunet** [comment]
Branches _should_ be solved for now, but tags have the same issue :/
